name: 'publish'

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          echo "${{ secrets.PAT }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin
          docker build -f Dockerfile.production . --tag ghcr.io/shapeshiftone/foxfrens:${GITHUB_REF#refs/tags/}
          docker tag ghcr.io/shapeshiftone/foxfrens:${GITHUB_REF#refs/tags/} ghcr.io/shapeshiftone/foxfrens:latest
          docker push ghcr.io/shapeshiftone/foxfrens:${GITHUB_REF#refs/tags/}
          docker push ghcr.io/shapeshiftone/foxfrens:latest
